"""Generate MP3 decoder test vectors from ffmpeg.

The decoder is written from the format specification, so it needs ground truth
that does not come from another decoder's source: ffmpeg encodes a known signal
to MP3 and decodes it back to PCM, and the test compares our output against that
PCM.

Only a window of the reference is kept. A few thousand samples is plenty to
catch a wrong Huffman table, a mis-signed IMDCT or a swapped stereo mode, and
storing whole clips would put hundreds of kilobytes of test data in a firmware
repository.

Bit-exactness is not the goal and is not achievable: the spec leaves rounding in
the IMDCT and the synthesis filterbank to the implementation. The test uses an
error bound instead, and searches for the alignment offset because encoders
prepend a delay that ffmpeg compensates and a raw frame decoder does not.

    python tools/gen_mp3_vectors.py

Writes test/test_mp3pcm/vectors.h. Requires ffmpeg on PATH.
"""

import os
import struct
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "test", "test_mp3pcm", "vectors.h")

WINDOW_FRAMES = 4096

SKIP_FRAMES = 2048

VECTORS = [
    ("sine_mono_64k", "sine=frequency=440:duration=0.4", 1, 44100, "64k", []),
    ("sine_stereo_128k", "sine=frequency=440:duration=0.4", 2, 44100, "128k", []),
    ("noise_stereo_320k", "anoisesrc=duration=0.4:color=pink:seed=1", 2, 44100, "320k", []),
    ("sweep_stereo_128k_48k", "sine=frequency=1000:duration=0.4", 2, 48000, "128k", []),
    ("noise_stereo_32khz", "anoisesrc=duration=0.4:color=white:seed=7", 2, 32000, "128k", []),
    ("clicks_stereo_128k",
     "aevalsrc='0.9*sin(2*PI*900*t)*lt(mod(t*20\\,1)\\,0.02)':d=0.4:s=44100", 2, 44100, "128k",
     []),
]


def run(args):
    proc = subprocess.run(args, capture_output=True)
    if proc.returncode != 0:
        raise SystemExit(
            "command failed: %s\n%s" % (" ".join(args), proc.stderr.decode("utf-8", "replace"))
        )
    return proc.stdout


def build(name, source, channels, rate, bitrate, extra, tmp):
    mp3_path = os.path.join(tmp, name + ".mp3")

    run(["ffmpeg", "-y", "-loglevel", "error", "-f", "lavfi", "-i", source,
         "-ac", str(channels), "-ar", str(rate), "-b:a", bitrate,
         "-codec:a", "libmp3lame"] + extra + [mp3_path])

    pcm = run(["ffmpeg", "-loglevel", "error", "-i", mp3_path,
               "-f", "s16le", "-acodec", "pcm_s16le", "-"])

    with open(mp3_path, "rb") as f:
        mp3 = f.read()

    total = len(pcm) // 2
    samples = struct.unpack("<%dh" % total, pcm[: total * 2])

    start = SKIP_FRAMES * channels
    end = start + WINDOW_FRAMES * channels
    if end > len(samples):
        raise SystemExit(
            "%s: reference decode is %d frames, need %d -- lengthen the clip"
            % (name, len(samples) // channels, SKIP_FRAMES + WINDOW_FRAMES)
        )
    return mp3, samples[start:end], rate, channels


def emit_bytes(out, name, data):
    out.write("inline constexpr uint8_t %s[] = {\n" % name)
    for i in range(0, len(data), 16):
        row = ", ".join("0x%02X" % b for b in data[i : i + 16])
        out.write("    %s,\n" % row)
    out.write("};\n\n")


def emit_samples(out, name, data):
    out.write("inline constexpr int16_t %s[] = {\n" % name)
    for i in range(0, len(data), 12):
        row = ", ".join("%d" % s for s in data[i : i + 12])
        out.write("    %s,\n" % row)
    out.write("};\n\n")


def main():
    built = []
    with tempfile.TemporaryDirectory() as tmp:
        for name, source, channels, rate, bitrate, extra in VECTORS:
            print("building %s ..." % name)
            built.append((name,) + build(name, source, channels, rate, bitrate, extra, tmp))

    with open(OUT, "w") as out:
        out.write("// GENERATED by tools/gen_mp3_vectors.py -- DO NOT EDIT.\n")
        out.write("//\n")
        out.write("// Encoded and decoded by ffmpeg from synthetic signals. `pcm` holds %d\n"
                  % WINDOW_FRAMES)
        out.write("// frames of the reference decode, starting %d frames in.\n" % SKIP_FRAMES)
        out.write("#pragma once\n\n#include <cstdint>\n\n")
        out.write("namespace mp3vectors {\n\n")
        out.write("inline constexpr int kWindowFrames = %d;\n" % WINDOW_FRAMES)
        out.write("inline constexpr int kSkipFrames = %d;\n\n" % SKIP_FRAMES)

        for name, mp3, pcm, rate, channels in built:
            out.write("// %s: %d Hz, %d ch, %d bytes encoded\n" % (name, rate, channels, len(mp3)))
            emit_bytes(out, "k%s_mp3" % name, mp3)
            emit_samples(out, "k%s_pcm" % name, pcm)
            out.write("inline constexpr int k%s_rate = %d;\n" % (name, rate))
            out.write("inline constexpr int k%s_channels = %d;\n\n" % (name, channels))

        out.write("}  // namespace mp3vectors\n")

    print("wrote %s (%d bytes)" % (OUT, os.path.getsize(OUT)))


if __name__ == "__main__":
    sys.exit(main())
