#!/usr/bin/env python3
"""Regenerate test/test_gifplayer/gif_fixtures.h.

The GifPlayer tests need real GIF bitstreams, and hand-writing those is
unreadable. This builds them with Pillow and emits C arrays. Run it after
changing a fixture's shape; the generated header is committed so the test
suite does not depend on Pillow.

    pip install pillow && python tools/gen_gif_fixtures.py

Fixtures are kept as small as the property under test allows: the
over-budget ones use 32x8 frames so the 16 KB pre-decode budget is crossed
in 33 frames instead of 129.
"""

import io
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, os.pardir, "test", "test_gifplayer", "gif_fixtures.h")

OVER_BUDGET_FRAMES = 33


def encode(frames, durations, transparency=None):
    buf = io.BytesIO()
    kwargs = dict(format="GIF", save_all=True, append_images=frames[1:],
                  duration=durations, loop=0, disposal=1, optimize=True)
    if transparency is not None:
        kwargs["transparency"] = transparency
    frames[0].save(buf, **kwargs)
    return buf.getvalue()


def solid(w, h, rgb):
    return Image.new("RGB", (w, h), rgb)


def paletted(w, h, palette, fill=0):
    im = Image.new("P", (w, h), fill)
    im.putpalette(palette + [0] * (768 - len(palette)))
    return im


def two_frames_8x8():
    """Red then green, 200/300 ms - basic playback and per-frame delays."""
    return encode([solid(8, 8, (255, 0, 0)), solid(8, 8, (0, 255, 0))], [200, 300])


def two_frames_32x8():
    """Full-width blue then white - 32x8 must survive at native size."""
    return encode([solid(32, 8, (0, 0, 255)), solid(32, 8, (255, 255, 255))], [100, 100])


def many_frames_32x8():
    """Over the pre-decode budget: exercises the streaming fallback."""
    frames = [solid(32, 8, (255, 0, 0) if i % 2 == 0 else (0, 0, 255))
              for i in range(OVER_BUDGET_FRAMES)]
    return encode(frames, [50] * OVER_BUDGET_FRAMES)


def transparent_static():
    """8x8, left half red, right half transparent - must render black."""
    im = paletted(8, 8, [0, 0, 0, 255, 0, 0])
    for y in range(8):
        for x in range(4):
            im.putpixel((x, y), 1)
    buf = io.BytesIO()
    im.save(buf, format="GIF", transparency=0)
    return buf.getvalue()


def transparent_anim():
    """Solid green, then a blue 4x4 with the rest transparent (green shows through)."""
    pal = [0, 0, 0, 0, 255, 0, 0, 0, 255]
    f1 = paletted(8, 8, pal, fill=1)
    f2 = paletted(8, 8, pal, fill=0)
    for y in range(4):
        for x in range(4):
            f2.putpixel((x, y), 2)
    return encode([f1, f2], [200, 200], transparency=0)


def transparent_many_frames_32x8():
    """Over budget AND transparent: the streaming path's first frame must be black."""
    pal = [0, 0, 0, 255, 0, 0, 0, 0, 255]
    frames = []
    for i in range(OVER_BUDGET_FRAMES):
        f = paletted(32, 8, pal, fill=0)
        idx = 1 if i % 2 == 0 else 2
        for y in range(8):
            for x in range(16):
                f.putpixel((x, y), idx)
        frames.append(f)
    return encode(frames, [50] * OVER_BUDGET_FRAMES, transparency=0)


def c_array(name, data):
    lines = [f"static const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    lines.append("};")
    lines.append(f"static const unsigned int {name}_len = {len(data)};")
    return "\n".join(lines)


FIXTURES = [
    ("kGif8x8TwoFrames", two_frames_8x8),
    ("kGif32x8TwoFrames", two_frames_32x8),
    ("kGif32x8ManyFrames", many_frames_32x8),
    ("kGifTransparentStatic", transparent_static),
    ("kGifTransparentAnim", transparent_anim),
    ("kGifTransparentManyFrames", transparent_many_frames_32x8),
]


def main():
    out = [
        "// Generated by tools/gen_gif_fixtures.py -- do not edit by hand.",
        "// Small real GIF bitstreams backing the GifPlayer tests.",
        "#pragma once",
        "",
    ]
    for name, build in FIXTURES:
        data = build()
        out.append(c_array(name, data))
        out.append("")
        print(f"{name}: {len(data)} bytes")
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(out))
    print("wrote", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
