
import gzip
import hashlib
import os
import shutil
import subprocess
import sys
import tempfile

Import("env")

BUDGET = 80 * 1024
SRC = os.path.join(env["PROJECT_DIR"], "webui", "index.html")
OUT = os.path.join(env["PROJECT_DIR"], "src", "transport", "http", "WebUiAsset.h")

MINIFIER = "html-minifier-terser@7.2.0"
MINIFY_ARGS = [
    "--collapse-whitespace",
    "--conservative-collapse",
    "--remove-comments",
    "--minify-css",
    "true",
    "--minify-js",
    "true",
]

sys.path.insert(0, os.path.join(env["PROJECT_DIR"], "scripts"))
import berry_api


def refresh_berry_api():
    if berry_api.inject(env["PROJECT_DIR"], SRC):
        print("webui: regenerated the Berry API table in webui/index.html")


def minify(src_path):
    npx = shutil.which("npx") or shutil.which("npx.cmd")
    if not npx:
        raise SystemExit(
            "webui: npx (Node.js) not found on PATH, and the web UI is minified with "
            "%s before it is embedded. Install Node.js, or run the build with an "
            "already-populated npx cache." % MINIFIER
        )
    fd, tmp = tempfile.mkstemp(suffix=".html")
    os.close(fd)
    try:
        proc = subprocess.run(
            [npx, "--yes", MINIFIER] + MINIFY_ARGS + ["-o", tmp, src_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        if proc.returncode != 0:
            raise SystemExit(
                "webui: %s failed (exit %d):\n%s"
                % (MINIFIER, proc.returncode, proc.stdout.decode("utf-8", "replace"))
            )
        with open(tmp, "rb") as f:
            return f.read()
    finally:
        os.remove(tmp)


def build_webui_asset():
    with open(SRC, "rb") as f:
        raw = f.read()
    src_md5 = hashlib.md5(raw).hexdigest()

    if os.path.exists(OUT):
        with open(OUT, "r") as f:
            if src_md5 in f.read():
                return

    mini = minify(SRC)
    gz = gzip.compress(mini, compresslevel=9, mtime=0)
    if len(gz) > BUDGET:
        raise SystemExit(
            "webui: gzipped asset is %d B, over the %d KB budget (%d B). "
            "Trim webui/index.html." % (len(gz), BUDGET // 1024, BUDGET)
        )
    etag = hashlib.md5(gz).hexdigest()

    lines = [
        "#pragma once",
        "// GENERATED by scripts/build_webui.py from webui/index.html - DO NOT EDIT.",
        "// %d B raw -> %d B minified -> %d B gzipped (budget %d KB)."
        % (len(raw), len(mini), len(gz), BUDGET // 1024),
        "// ETag = MD5 of the gzip stream. SRC-MD5 %s (source-unchanged check)."
        % src_md5,
        "",
        "#include <pgmspace.h>",
        "",
        "namespace awtrix {",
        "",
        'inline constexpr char WEBUI_ETAG[] = "\\"%s\\"";' % etag,
        "inline constexpr unsigned WEBUI_GZ_LEN = %d;" % len(gz),
        "inline const uint8_t WEBUI_GZ[] PROGMEM = {",
    ]
    for i in range(0, len(gz), 20):
        chunk = gz[i : i + 20]
        lines.append("    " + "".join("0x%02x," % b for b in chunk))
    lines += ["};", "", "}  // namespace awtrix", ""]

    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(
        "webui: embedded %d B raw -> %d B minified -> %d B gzipped (ETag %s)"
        % (len(raw), len(mini), len(gz), etag)
    )


refresh_berry_api()
build_webui_asset()
