"""Generate the ESP32 partition table for a (SoC, flash size) pair.

Two rules produce every table this project ships:

  * The app slot is derived from the *firmware*, never from the available flash:
    measured binary + at least 20 % growth margin, rounded up to 64 KB. One slot
    size for every SoC and every flash variant. Sizing slots by available flash
    would make an 8 MB board pay for headroom only a 16 MB board could afford,
    and it would lose megabytes of icon storage doing it.
  * SPIFFS takes whatever is left, minus a 64 KB coredump region at the very end
    of flash.

Keeping the slot size uniform is a policy choice, not a hardware requirement --
ESP32 app images are position independent, which is what makes A/B OTA work at
all. Uniformity buys a single failure boundary instead: a firmware that outgrows
its slot fails on every board at once, rather than on some of them. A per-SoC
size would put that boundary in a different place on each chip, so the SoC with
the smaller slot would refuse a build the other still accepts.

The size is what the 4 MB ESP32 can carry: two 1728 KB slots leave it exactly the
512 KB SPIFFS minimum. Raising it is a 4 MB decision before it is anything else.

Runs two ways:

  * as a PlatformIO pre-script, taking the SoC and flash size from the board and
    pointing the build at the generated file
  * standalone, for CI, which needs tables for variants nobody builds locally:

        python scripts/gen_partitions.py --soc esp32s3 --flash-size 16MB
"""

import argparse
import os
import sys

APP_SLOT = {
    "esp32": 0x1B0000,
    "esp32s3": 0x1B0000,
}

FACTORY_FLASH_SIZES = {
    "esp32": ["4MB", "8MB", "16MB"],
    "esp32s3": ["8MB", "16MB"],
}

ALIGN = 0x10000
APP_START = 0x10000
COREDUMP_SIZE = 0x10000

MIN_SPIFFS = 0x80000


class LayoutError(Exception):
    pass


def parse_flash_size(text):
    """Accept '16MB', '16M' or a raw byte count."""
    s = str(text).strip().upper().rstrip("B")
    if s.endswith("M"):
        return int(s[:-1]) * 1024 * 1024
    if s.endswith("K"):
        return int(s[:-1]) * 1024
    return int(s, 0)


def layout(soc, flash_bytes):
    """Return the partition list as (name, type, subtype, offset, size) tuples."""
    if soc not in APP_SLOT:
        raise LayoutError("unknown SoC %r (known: %s)" % (soc, ", ".join(sorted(APP_SLOT))))
    slot = APP_SLOT[soc]

    app0 = APP_START
    app1 = app0 + slot
    if app1 % ALIGN:
        raise LayoutError(
            "app slot 0x%X leaves app1 at 0x%X, which is not 64 KB aligned" % (slot, app1)
        )

    coredump = flash_bytes - COREDUMP_SIZE
    spiffs = app1 + slot
    spiffs_size = coredump - spiffs

    if spiffs_size < MIN_SPIFFS:
        raise LayoutError(
            "%s with %d MB flash leaves only %d KB for SPIFFS (minimum %d KB): "
            "two %d KB app slots do not fit"
            % (soc, flash_bytes // (1024 * 1024), spiffs_size // 1024,
               MIN_SPIFFS // 1024, slot // 1024)
        )

    return [
        ("nvs", "data", "nvs", 0x9000, 0x5000),
        ("otadata", "data", "ota", 0xE000, 0x2000),
        ("app0", "app", "ota_0", app0, slot),
        ("app1", "app", "ota_1", app1, slot),
        ("spiffs", "data", "spiffs", spiffs, spiffs_size),
        ("coredump", "data", "coredump", coredump, COREDUMP_SIZE),
    ]


def render(soc, flash_bytes):
    parts = layout(soc, flash_bytes)
    spiffs = next(p for p in parts if p[0] == "spiffs")
    lines = [
        "# GENERATED by scripts/gen_partitions.py -- DO NOT EDIT.",
        "# %s, %d MB flash: %d KB per app slot, %d KB SPIFFS."
        % (soc, flash_bytes // (1024 * 1024), APP_SLOT[soc] // 1024, spiffs[4] // 1024),
        "# Name,     Type, SubType,  Offset,   Size,",
    ]
    for name, ptype, subtype, offset, size in parts:
        lines.append(
            "%-10s %-5s %-9s %-10s 0x%X,"
            % (name + ",", ptype + ",", subtype + ",", "0x%X," % offset, size)
        )
    return "\n".join(lines) + "\n"


def _standalone(argv):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--soc", required=True, choices=sorted(APP_SLOT))
    ap.add_argument("--flash-size", required=True, help="e.g. 4MB, 8MB, 16MB")
    ap.add_argument("-o", "--output", help="write here instead of stdout")
    args = ap.parse_args(argv)

    try:
        csv = render(args.soc, parse_flash_size(args.flash_size))
    except LayoutError as e:
        raise SystemExit("gen_partitions: %s" % e)

    if args.output:
        with open(args.output, "w") as f:
            f.write(csv)
    else:
        sys.stdout.write(csv)


def _platformio():
    board = env.BoardConfig()  # noqa: F821 - injected by SCons
    soc = board.get("build.mcu")
    flash = parse_flash_size(board.get("upload.flash_size", "4MB"))

    try:
        csv = render(soc, flash)
    except LayoutError as e:
        raise SystemExit("gen_partitions: %s" % e)

    build_dir = env.subst("$BUILD_DIR")  # noqa: F821
    if not os.path.isdir(build_dir):
        os.makedirs(build_dir)
    out = os.path.join(build_dir, "partitions.csv")

    if not os.path.exists(out) or open(out).read() != csv:
        with open(out, "w") as f:
            f.write(csv)

    board.update("build.partitions", out)
    spiffs = next(p for p in layout(soc, flash) if p[0] == "spiffs")
    print(
        "partitions: %s, %d MB flash -> %d KB per app slot, %d KB SPIFFS"
        % (soc, flash // (1024 * 1024), APP_SLOT[soc] // 1024, spiffs[4] // 1024)
    )


try:
    Import("env")  # noqa: F821
except NameError:
    if __name__ == "__main__":
        _standalone(sys.argv[1:])
else:
    _platformio()
