#!/usr/bin/env python3
"""Regenerate src/core/script/PreludeSolidified.h from Prelude.h.

The prelude is ~17 KB of Berry that every device otherwise parses into heap
protos at each boot. Solidifying it emits the compiled form as C const data, so
the protos, constants and strings live in flash .rodata instead.

Run this after ANY edit to core/script/Prelude.h or to the binding set in
core/script/ScriptBindings.cpp, and commit the result together with
lib/berry/generate (the const string table changes with it).

    python scripts/gen_prelude_solidified.py

Pipeline, and why each step is shaped this way:

1. The prelude source is taken by COMPILING tools/solidify/dump_prelude.cpp and
   running it, never by scraping Prelude.h. Prelude.h splices C macros into the
   Berry text (AWTRIX_MAX_MQTT_SUBS), so the raw-string literal is broken into
   concatenated pieces; text extraction silently drops whatever surrounds a
   splice, which once deleted the mqtt subscription cap from a generated
   prelude and was caught only by a unit test.

2. The host bindings are scraped from ScriptBindings.cpp and registered in the
   generator VM. Berry rejects an undeclared-global read at compile time, so
   they must exist -- but the generator compiles with the named-global option
   so they are emitted BY NAME (OP_GETNGBL), letting the bytecode bind to the
   firmware's real registrations rather than to any global index.

3. Berry is built twice. The generator needs a tree with BE_USE_SOLIDIFY_MODULE
   and BE_USE_DEBUG_MODULE on (solidify calls be_print_inst, which upstream
   declares only under the debug module), so an isolated copy is made and its
   generate/ produced by coc for that config. The committed lib/berry keeps
   both modules off.

4. coc is finally re-run over lib/berry/src AND the generated header, because
   solidify emits &be_const_str_X references and coc is what defines those
   symbols in the shared const string table.
"""

import hashlib
import os
import re
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BERRY = os.path.join(ROOT, "lib", "berry")
COC = os.path.join(ROOT, "tools", "coc", "coc")
OUT_HEADER = os.path.join(ROOT, "src", "core", "script", "PreludeSolidified.h")
BUILD = os.path.join(ROOT, ".pio", "solidify")

STAMP_PREFIX = "// input-sha256: "

BANNER = """#pragma once
// GENERATED by scripts/gen_prelude_solidified.py - DO NOT EDIT BY HAND.
//
// The shared Berry prelude (core/script/Prelude.h), compiled at build time and
// emitted as const data: every proto, constant and string below lands in flash
// .rodata instead of being parsed and built on the heap at each boot.
//
// Host bindings are referenced BY NAME (OP_GETNGBL), not by global index, so
// the bytecode binds to whatever ScriptBindings.cpp registered at runtime.
//
// The be_const_str_* symbols come from lib/berry/generate, which this script
// regenerates with coc over both lib/berry/src and this header. Commit the two
// together.
//
// C-only: be_constobj.h defines its macros under #ifndef __cplusplus. Included
// from PreludeSolidifiedLoad.c.

#include "be_constobj.h"

"""


def cxx():
    """g++ from PATH, else the portable w64devkit docs/advanced/building.md documents."""
    if shutil.which("g++"):
        return "g++"
    fallback = os.environ.get("W64DEVKIT", r"D:\tools\w64devkit")
    exe = os.path.join(fallback, "bin", "g++.exe")
    if os.path.isfile(exe):
        return exe
    sys.exit("gen_prelude_solidified: no g++ on PATH and no w64devkit at %s" % fallback)


def cc():
    if shutil.which("gcc"):
        return "gcc"
    fallback = os.environ.get("W64DEVKIT", r"D:\tools\w64devkit")
    exe = os.path.join(fallback, "bin", "gcc.exe")
    if os.path.isfile(exe):
        return exe
    sys.exit("gen_prelude_solidified: no gcc found")


def run(cmd, **kw):
    r = subprocess.run(cmd, **kw)
    if r.returncode != 0:
        sys.exit("gen_prelude_solidified: command failed: %s" % " ".join(map(str, cmd)))
    return r


def run_coc(out_dir, inputs, config):
    run([sys.executable, COC, "-o", out_dir] + list(inputs) + ["-c", config],
        cwd=os.path.dirname(COC))


def prelude_source():
    """Compile and run dump_prelude: the string the firmware itself compiles.

    Newlines are normalised because Windows writes stdout in text mode, so the
    same prelude arrives with CRLF there and LF on Linux. The fingerprint would
    otherwise depend on which machine generated the header, and a header made on
    Windows could never satisfy the CI check.
    """
    exe = os.path.join(BUILD, "dump_prelude.exe")
    run([cxx(), "-std=gnu++17", "-O1", "-w", "-I" + os.path.join(ROOT, "src"),
         os.path.join(ROOT, "tools", "solidify", "dump_prelude.cpp"), "-o", exe])
    out = subprocess.run([exe], check=True, stdout=subprocess.PIPE).stdout
    return out.replace(b"\r\n", b"\n")


def native_names():
    """Every global ScriptBindings registers before the prelude runs."""
    path = os.path.join(ROOT, "src", "core", "script", "ScriptBindings.cpp")
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        names = re.findall(r'be_regfunc\(\s*\w+\s*,\s*"([^"]+)"', f.read())
    if not names:
        sys.exit("gen_prelude_solidified: found no be_regfunc bindings -- did the "
                 "registration style change?")
    return sorted(set(names))


def coc_escape(name):
    """Mirror tools/coc/coc_string.py escape_operator: the identifier coc uses
    for a string's be_const_str_* symbol."""
    name = re.sub("_X", "_X_", name)
    return re.sub("[^a-zA-Z0-9_]", lambda m: "_X{0:02X}".format(ord(m.group())), name)


def binding_name_anchor(names):
    """A block referencing every binding name via be_nested_str so the coc pass
    defines them in the const string table. be_regfunc() then interns each name
    against flash at boot instead of copying it onto the heap. Never read at
    runtime; must use the strtab-triggering be_nested_str, not the _weak form,
    or find_conststr() would still miss."""
    lines = [
        "/* Binding-name anchor: every global ScriptBindings.cpp registers,",
        " * referenced once so coc emits the names into the const string table",
        " * and be_regfunc() finds them in flash instead of interning per boot. */",
        "static const bvalue awtrix_binding_name_anchor[]",
        "    __attribute__((unused)) = {",
    ]
    lines += ["  be_nested_str(%s)," % coc_escape(n) for n in names]
    lines += ["};", ""]
    return "\n".join(lines)


def input_fingerprint(source=None, names=None):
    """Hash of the expanded prelude plus the binding names it may reference."""
    if source is None:
        source = prelude_source()
    if names is None:
        names = native_names()
    h = hashlib.sha256()
    h.update(source)
    h.update(b"\n--bindings--\n")
    h.update("\n".join(names).encode("utf-8"))
    return h.hexdigest()


def stamp_of(header_path):
    """The fingerprint recorded in a generated header, or None."""
    if not os.path.isfile(header_path):
        return None
    with open(header_path, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            if line.startswith(STAMP_PREFIX):
                return line[len(STAMP_PREFIX):].strip()
            if "be_local_closure" in line:
                break
    return None


def build_generator():
    """An isolated Berry with solidify+debug on, and a gen_prelude linked to it."""
    tree = os.path.join(BUILD, "berry-gen")
    if os.path.isdir(tree):
        shutil.rmtree(tree)
    shutil.copytree(BERRY, tree)

    conf = os.path.join(tree, "berry_conf.h")
    with open(conf, "r", encoding="utf-8") as f:
        text = f.read()
    for macro in ("BE_USE_SOLIDIFY_MODULE", "BE_USE_DEBUG_MODULE"):
        text = re.sub(r"(#define\s+%s\s+)0" % macro, r"\g<1>1", text)
    with open(conf, "w", encoding="utf-8") as f:
        f.write(text)

    gen_dir = os.path.join(tree, "generate")
    for f in os.listdir(gen_dir):
        if f.endswith(".h"):
            os.remove(os.path.join(gen_dir, f))
    run_coc(gen_dir, [os.path.join(tree, "src")], conf)

    objs = os.path.join(BUILD, "obj")
    if os.path.isdir(objs):
        shutil.rmtree(objs)
    os.makedirs(objs)
    inc = ["-I" + os.path.join(tree, "src"), "-I" + tree]
    sources = [os.path.join(tree, "src", f) for f in os.listdir(os.path.join(tree, "src"))
               if f.endswith(".c")]
    sources += [os.path.join(tree, "default", "be_port.c"),
                os.path.join(tree, "default", "be_modtab.c")]
    for src in sources:
        obj = os.path.join(objs, os.path.basename(src)[:-2] + ".o")
        run([cc(), "-std=gnu99", "-O1", "-w"] + inc + ["-c", src, "-o", obj])

    exe = os.path.join(BUILD, "gen_prelude.exe")
    run([cxx(), "-std=gnu++17", "-O0", "-w"] + inc +
        [os.path.join(ROOT, "tools", "solidify", "gen_prelude.cpp")] +
        [os.path.join(objs, f) for f in sorted(os.listdir(objs))] + ["-o", exe])
    return exe


def main():
    os.makedirs(BUILD, exist_ok=True)

    source = prelude_source()
    names = native_names()
    fingerprint = input_fingerprint(source, names)
    names_file = os.path.join(BUILD, "natives.txt")
    with open(names_file, "w", encoding="utf-8") as f:
        f.write("\n".join(names))

    gen = build_generator()
    solidified = subprocess.run([gen, names_file], input=source, check=True,
                                stdout=subprocess.PIPE).stdout.decode("utf-8")
    if "be_local_closure" not in solidified:
        sys.exit("gen_prelude_solidified: generator produced no closure")

    solidified = solidified.replace("be_local_closure(main,",
                                    "be_local_closure(awtrix_prelude,", 1)
    with open(OUT_HEADER, "w", encoding="utf-8", newline="\n") as f:
        f.write(BANNER)
        f.write(STAMP_PREFIX + fingerprint + "\n\n")
        f.write(solidified)
        f.write("\n")
        f.write(binding_name_anchor(names))

    scan = os.path.join(BUILD, "scan")
    if os.path.isdir(scan):
        shutil.rmtree(scan)
    os.makedirs(scan)
    shutil.copy(OUT_HEADER, scan)
    run_coc(os.path.join(BERRY, "generate"),
            [os.path.join(BERRY, "src"), scan],
            os.path.join(BERRY, "berry_conf.h"))

    print("prelude solidified: %d bytes of source -> %s (%d bytes); "
          "lib/berry/generate refreshed"
          % (len(source), os.path.relpath(OUT_HEADER, ROOT), len(solidified)))


if __name__ == "__main__":
    main()
