"""Generates the IANA-zone -> POSIX-TZ table the WebUI's timezone picker uses.

The device only ever speaks POSIX TZ strings: `configTzTime()` hands them
straight to the C library, and the M-rules inside them are what makes the clock
follow daylight saving without anybody pressing a button twice a year. Those
strings are unreadable, so the WebUI lets the user pick `Europe/Berlin` and
looks the string up here.

Two inputs, each the authority on its half:

  * `scripts/zone1970.tab`, vendored from the IANA distribution, names the
    zones that are worth offering -- one per inhabited region, aliases like
    `Asia/Calcutta` and legacy spellings like `US/Pacific` already dropped.
  * The `tzdata` Python package supplies the compiled TZif files. Every TZif
    v2+ file ends with the POSIX rule for all future dates on its own line, and
    that footer IS the string we want, so no rule is guessed here.

Not a build step. The table only moves when IANA publishes a new release, so it
is regenerated by hand and committed:

    pip install tzdata
    curl -o scripts/zone1970.tab https://raw.githubusercontent.com/eggert/tz/main/zone1970.tab
    python scripts/tz_data.py --inject
"""

import importlib.resources as resources
import os

BEGIN = "/* TZ-DATA-START */"
END = "/* TZ-DATA-END */"

TAB = os.path.join(os.path.dirname(os.path.abspath(__file__)), "zone1970.tab")


def _zoneinfo():
    return resources.files("tzdata").joinpath("zoneinfo")


def _canonical_zones():
    """Zone names from zone1970.tab: canonical, inhabited, no aliases.

    UTC is not in that file -- it describes places, and UTC is not one -- but a
    picker without it would send anyone running a headless clock back to the
    POSIX string, so it is added here.
    """
    with open(TAB, "r", encoding="utf-8") as f:
        rows = [l for l in f if l.strip() and not l.startswith("#")]
    names = {r.split("\t")[2].strip() for r in rows}
    names.add("UTC")
    return sorted(names)


def _posix_rule(name):
    """The POSIX TZ footer of one TZif file, or None if the file has no v2 block."""
    data = _zoneinfo().joinpath(*name.split("/")).read_bytes()
    parts = data.split(b"\n")
    if len(parts) < 2 or parts[-1] != b"":
        return None
    rule = parts[-2].decode("ascii", "replace")
    return rule or None


def table():
    """{posix rule: [zone names]}, sorted, ready to render.

    Antarctica sorts last within a rule. A rule written straight through the API
    carries no zone name, and the WebUI names it after the first zone that runs
    on the rule -- `Australia/Hobart` is a defensible answer there,
    `Antarctica/Macquarie` is not.
    """
    out = {}
    for name in _canonical_zones():
        rule = _posix_rule(name)
        if rule:
            out.setdefault(rule, []).append(name)
    return {
        rule: sorted(zones, key=lambda n: (n.startswith("Antarctica/"), n))
        for rule, zones in sorted(out.items())
    }


def render_js():
    """One JS literal: rule first, then the zones that share it.

    Grouping by rule is what keeps this affordable -- 598 zones collapse onto
    about 90 distinct rules, and the repeated `Europe/` prefixes compress away
    in the gzip the WebUI is served as.
    """
    import tzdata

    iana = tzdata.IANA_VERSION
    rows = ",\n".join(
        "['%s','%s']" % (rule, " ".join(zones)) for rule, zones in table().items()
    )
    return (
        "/* GENERATED by scripts/tz_data.py from IANA tzdata %s - DO NOT EDIT BY HAND.\n"
        "   Each row is one POSIX TZ rule and the zones that follow it. */\n"
        "const TZ_TABLE=[\n%s];" % (iana, rows)
    )


def block():
    return BEGIN + "\n" + render_js() + "\n" + END


def inject(project_dir, path=None):
    """Rewrites the generated region inside webui/index.html, in place.

    Same contract as scripts/berry_api.py: writing it back rather than patching
    a throwaway copy is what lets the simulator, which serves the file straight
    from disk, see the table the device sees.
    """
    path = path or os.path.join(project_dir, "webui", "index.html")
    with open(path, "r", encoding="utf-8", newline="") as f:
        html = f.read()
    start, end = html.find(BEGIN), html.find(END)
    if start < 0 or end < 0 or end < start:
        raise SystemExit(
            "tz data: the %s / %s markers are missing from %s" % (BEGIN, END, path)
        )
    updated = html[:start] + block() + html[end + len(END):]
    if updated == html:
        return False
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(updated)
    return True


if __name__ == "__main__":
    import sys

    args = [a for a in sys.argv[1:] if a != "--inject"]
    root = args[0] if args else os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if "--inject" in sys.argv:
        print("tz data: %s" % ("regenerated webui/index.html" if inject(root) else "already current"))
    else:
        print(render_js())
