set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv7)
if(NOT TC002_TOOLCHAIN)
  set(TC002_TOOLCHAIN "$ENV{TC002_TOOLCHAIN}" CACHE PATH "Official TC002 toolchain")
endif()
if(NOT TC002_TOOLCHAIN)
  message(FATAL_ERROR "Set TC002_TOOLCHAIN to the extracted official toolchain directory")
endif()
set(TC002_TRIPLE arm-none-linux-gnueabihf CACHE STRING "Cross compiler target triple")
set(CMAKE_C_COMPILER "${TC002_TOOLCHAIN}/bin/${TC002_TRIPLE}-gcc")
set(CMAKE_CXX_COMPILER "${TC002_TOOLCHAIN}/bin/${TC002_TRIPLE}-g++")
set(CMAKE_STRIP "${TC002_TOOLCHAIN}/bin/${TC002_TRIPLE}-strip")
set(CMAKE_C_FLAGS_INIT "-mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard")
set(CMAKE_CXX_FLAGS_INIT "-mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
